/*
 * can.c
 *
 *  Created on: Apr 23, 2024
 *      Author: Steven
 */

/**
 * The MIT License (MIT)
 *
 * Copyright (c) 2018-2019 Erik Moqvist
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

/**
 * This file was generated by cantools version 39.4.1 Sun Jun  2 21:53:40 2024.
 */

#include <string.h>

#include "can.h"

static inline uint8_t pack_left_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_left_shift_u16(
    uint16_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_left_shift_u32(
    uint32_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_left_shift_u64(
    uint64_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_right_shift_u16(
    uint16_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value >> shift) & mask);
}

static inline uint8_t pack_right_shift_u32(
    uint32_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value >> shift) & mask);
}

static inline uint8_t pack_right_shift_u64(
    uint64_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value >> shift) & mask);
}

static inline uint16_t unpack_left_shift_u16(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint16_t)((uint16_t)(value & mask) << shift);
}

static inline uint32_t unpack_left_shift_u32(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint32_t)((uint32_t)(value & mask) << shift);
}

static inline uint64_t unpack_left_shift_u64(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint64_t)((uint64_t)(value & mask) << shift);
}

static inline uint8_t unpack_right_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value & mask) >> shift);
}

static inline uint16_t unpack_right_shift_u16(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint16_t)((uint16_t)(value & mask) >> shift);
}

static inline uint32_t unpack_right_shift_u32(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint32_t)((uint32_t)(value & mask) >> shift);
}

static inline uint64_t unpack_right_shift_u64(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint64_t)((uint64_t)(value & mask) >> shift);
}

int ucr_01_front_analog_pack(
    uint8_t *dst_p,
    const struct ucr_01_front_analog_t *src_p,
    size_t size)
{
    if (size < 16u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 16);

    dst_p[0] |= pack_left_shift_u16(src_p->analog1, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(src_p->analog1, 8u, 0xffu);
    dst_p[2] |= pack_left_shift_u16(src_p->analog2, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(src_p->analog2, 8u, 0xffu);
    dst_p[4] |= pack_left_shift_u16(src_p->analog3, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u16(src_p->analog3, 8u, 0xffu);
    dst_p[6] |= pack_left_shift_u16(src_p->analog4, 0u, 0xffu);
    dst_p[7] |= pack_right_shift_u16(src_p->analog4, 8u, 0xffu);
    dst_p[8] |= pack_left_shift_u16(src_p->analog5, 0u, 0xffu);
    dst_p[9] |= pack_right_shift_u16(src_p->analog5, 8u, 0xffu);
    dst_p[10] |= pack_left_shift_u16(src_p->analog6, 0u, 0xffu);
    dst_p[11] |= pack_right_shift_u16(src_p->analog6, 8u, 0xffu);
    dst_p[12] |= pack_left_shift_u16(src_p->analog7, 0u, 0xffu);
    dst_p[13] |= pack_right_shift_u16(src_p->analog7, 8u, 0xffu);
    dst_p[14] |= pack_left_shift_u16(src_p->analog8, 0u, 0xffu);
    dst_p[15] |= pack_right_shift_u16(src_p->analog8, 8u, 0xffu);

    return (16);
}

int ucr_01_front_analog_unpack(
    struct ucr_01_front_analog_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 16u) {
        return (-EINVAL);
    }

    dst_p->analog1 = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    dst_p->analog1 |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    dst_p->analog2 = unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    dst_p->analog2 |= unpack_left_shift_u16(src_p[3], 8u, 0xffu);
    dst_p->analog3 = unpack_right_shift_u16(src_p[4], 0u, 0xffu);
    dst_p->analog3 |= unpack_left_shift_u16(src_p[5], 8u, 0xffu);
    dst_p->analog4 = unpack_right_shift_u16(src_p[6], 0u, 0xffu);
    dst_p->analog4 |= unpack_left_shift_u16(src_p[7], 8u, 0xffu);
    dst_p->analog5 = unpack_right_shift_u16(src_p[8], 0u, 0xffu);
    dst_p->analog5 |= unpack_left_shift_u16(src_p[9], 8u, 0xffu);
    dst_p->analog6 = unpack_right_shift_u16(src_p[10], 0u, 0xffu);
    dst_p->analog6 |= unpack_left_shift_u16(src_p[11], 8u, 0xffu);
    dst_p->analog7 = unpack_right_shift_u16(src_p[12], 0u, 0xffu);
    dst_p->analog7 |= unpack_left_shift_u16(src_p[13], 8u, 0xffu);
    dst_p->analog8 = unpack_right_shift_u16(src_p[14], 0u, 0xffu);
    dst_p->analog8 |= unpack_left_shift_u16(src_p[15], 8u, 0xffu);

    return (0);
}

int ucr_01_front_analog_init(struct ucr_01_front_analog_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct ucr_01_front_analog_t));

    return 0;
}

uint16_t ucr_01_front_analog_analog1_encode(double value)
{
    return (uint16_t)(value);
}

double ucr_01_front_analog_analog1_decode(uint16_t value)
{
    return ((double)value);
}

bool ucr_01_front_analog_analog1_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t ucr_01_front_analog_analog2_encode(double value)
{
    return (uint16_t)(value);
}

double ucr_01_front_analog_analog2_decode(uint16_t value)
{
    return ((double)value);
}

bool ucr_01_front_analog_analog2_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t ucr_01_front_analog_analog3_encode(double value)
{
    return (uint16_t)(value);
}

double ucr_01_front_analog_analog3_decode(uint16_t value)
{
    return ((double)value);
}

bool ucr_01_front_analog_analog3_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t ucr_01_front_analog_analog4_encode(double value)
{
    return (uint16_t)(value);
}

double ucr_01_front_analog_analog4_decode(uint16_t value)
{
    return ((double)value);
}

bool ucr_01_front_analog_analog4_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t ucr_01_front_analog_analog5_encode(double value)
{
    return (uint16_t)(value);
}

double ucr_01_front_analog_analog5_decode(uint16_t value)
{
    return ((double)value);
}

bool ucr_01_front_analog_analog5_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t ucr_01_front_analog_analog6_encode(double value)
{
    return (uint16_t)(value);
}

double ucr_01_front_analog_analog6_decode(uint16_t value)
{
    return ((double)value);
}

bool ucr_01_front_analog_analog6_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t ucr_01_front_analog_analog7_encode(double value)
{
    return (uint16_t)(value);
}

double ucr_01_front_analog_analog7_decode(uint16_t value)
{
    return ((double)value);
}

bool ucr_01_front_analog_analog7_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t ucr_01_front_analog_analog8_encode(double value)
{
    return (uint16_t)(value);
}

double ucr_01_front_analog_analog8_decode(uint16_t value)
{
    return ((double)value);
}

bool ucr_01_front_analog_analog8_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

int ucr_01_rear_analog_pack(
    uint8_t *dst_p,
    const struct ucr_01_rear_analog_t *src_p,
    size_t size)
{
    if (size < 16u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 16);

    dst_p[0] |= pack_left_shift_u16(src_p->analog1, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(src_p->analog1, 8u, 0xffu);
    dst_p[2] |= pack_left_shift_u16(src_p->analog2, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(src_p->analog2, 8u, 0xffu);
    dst_p[4] |= pack_left_shift_u16(src_p->analog3, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u16(src_p->analog3, 8u, 0xffu);
    dst_p[6] |= pack_left_shift_u16(src_p->analog4, 0u, 0xffu);
    dst_p[7] |= pack_right_shift_u16(src_p->analog4, 8u, 0xffu);
    dst_p[8] |= pack_left_shift_u16(src_p->analog5, 0u, 0xffu);
    dst_p[9] |= pack_right_shift_u16(src_p->analog5, 8u, 0xffu);
    dst_p[10] |= pack_left_shift_u16(src_p->analog6, 0u, 0xffu);
    dst_p[11] |= pack_right_shift_u16(src_p->analog6, 8u, 0xffu);
    dst_p[12] |= pack_left_shift_u16(src_p->analog7, 0u, 0xffu);
    dst_p[13] |= pack_right_shift_u16(src_p->analog7, 8u, 0xffu);
    dst_p[14] |= pack_left_shift_u16(src_p->analog8, 0u, 0xffu);
    dst_p[15] |= pack_right_shift_u16(src_p->analog8, 8u, 0xffu);

    return (16);
}

int ucr_01_rear_analog_unpack(
    struct ucr_01_rear_analog_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 16u) {
        return (-EINVAL);
    }

    dst_p->analog1 = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    dst_p->analog1 |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    dst_p->analog2 = unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    dst_p->analog2 |= unpack_left_shift_u16(src_p[3], 8u, 0xffu);
    dst_p->analog3 = unpack_right_shift_u16(src_p[4], 0u, 0xffu);
    dst_p->analog3 |= unpack_left_shift_u16(src_p[5], 8u, 0xffu);
    dst_p->analog4 = unpack_right_shift_u16(src_p[6], 0u, 0xffu);
    dst_p->analog4 |= unpack_left_shift_u16(src_p[7], 8u, 0xffu);
    dst_p->analog5 = unpack_right_shift_u16(src_p[8], 0u, 0xffu);
    dst_p->analog5 |= unpack_left_shift_u16(src_p[9], 8u, 0xffu);
    dst_p->analog6 = unpack_right_shift_u16(src_p[10], 0u, 0xffu);
    dst_p->analog6 |= unpack_left_shift_u16(src_p[11], 8u, 0xffu);
    dst_p->analog7 = unpack_right_shift_u16(src_p[12], 0u, 0xffu);
    dst_p->analog7 |= unpack_left_shift_u16(src_p[13], 8u, 0xffu);
    dst_p->analog8 = unpack_right_shift_u16(src_p[14], 0u, 0xffu);
    dst_p->analog8 |= unpack_left_shift_u16(src_p[15], 8u, 0xffu);

    return (0);
}

int ucr_01_rear_analog_init(struct ucr_01_rear_analog_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct ucr_01_rear_analog_t));

    return 0;
}

uint16_t ucr_01_rear_analog_analog1_encode(double value)
{
    return (uint16_t)(value);
}

double ucr_01_rear_analog_analog1_decode(uint16_t value)
{
    return ((double)value);
}

bool ucr_01_rear_analog_analog1_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t ucr_01_rear_analog_analog2_encode(double value)
{
    return (uint16_t)(value);
}

double ucr_01_rear_analog_analog2_decode(uint16_t value)
{
    return ((double)value);
}

bool ucr_01_rear_analog_analog2_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t ucr_01_rear_analog_analog3_encode(double value)
{
    return (uint16_t)(value);
}

double ucr_01_rear_analog_analog3_decode(uint16_t value)
{
    return ((double)value);
}

bool ucr_01_rear_analog_analog3_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t ucr_01_rear_analog_analog4_encode(double value)
{
    return (uint16_t)(value);
}

double ucr_01_rear_analog_analog4_decode(uint16_t value)
{
    return ((double)value);
}

bool ucr_01_rear_analog_analog4_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t ucr_01_rear_analog_analog5_encode(double value)
{
    return (uint16_t)(value);
}

double ucr_01_rear_analog_analog5_decode(uint16_t value)
{
    return ((double)value);
}

bool ucr_01_rear_analog_analog5_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t ucr_01_rear_analog_analog6_encode(double value)
{
    return (uint16_t)(value);
}

double ucr_01_rear_analog_analog6_decode(uint16_t value)
{
    return ((double)value);
}

bool ucr_01_rear_analog_analog6_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t ucr_01_rear_analog_analog7_encode(double value)
{
    return (uint16_t)(value);
}

double ucr_01_rear_analog_analog7_decode(uint16_t value)
{
    return ((double)value);
}

bool ucr_01_rear_analog_analog7_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t ucr_01_rear_analog_analog8_encode(double value)
{
    return (uint16_t)(value);
}

double ucr_01_rear_analog_analog8_decode(uint16_t value)
{
    return ((double)value);
}

bool ucr_01_rear_analog_analog8_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

int ucr_01_front_aero_pack(
    uint8_t *dst_p,
    const struct ucr_01_front_aero_t *src_p,
    size_t size)
{
    uint16_t temperature1;
    uint16_t temperature2;
    uint16_t temperature3;
    uint32_t pressure1;
    uint32_t pressure2;
    uint32_t pressure3;

    if (size < 16u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 16);

    pressure1 = (uint32_t)src_p->pressure1;
    dst_p[0] |= pack_left_shift_u32(pressure1, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u32(pressure1, 8u, 0xffu);
    dst_p[2] |= pack_right_shift_u32(pressure1, 16u, 0xffu);
    pressure2 = (uint32_t)src_p->pressure2;
    dst_p[3] |= pack_left_shift_u32(pressure2, 0u, 0xffu);
    dst_p[4] |= pack_right_shift_u32(pressure2, 8u, 0xffu);
    dst_p[5] |= pack_right_shift_u32(pressure2, 16u, 0xffu);
    pressure3 = (uint32_t)src_p->pressure3;
    dst_p[6] |= pack_left_shift_u32(pressure3, 0u, 0xffu);
    dst_p[7] |= pack_right_shift_u32(pressure3, 8u, 0xffu);
    dst_p[8] |= pack_right_shift_u32(pressure3, 16u, 0xffu);
    temperature1 = (uint16_t)src_p->temperature1;
    dst_p[9] |= pack_left_shift_u16(temperature1, 0u, 0xffu);
    dst_p[10] |= pack_right_shift_u16(temperature1, 8u, 0xffu);
    temperature2 = (uint16_t)src_p->temperature2;
    dst_p[11] |= pack_left_shift_u16(temperature2, 0u, 0xffu);
    dst_p[12] |= pack_right_shift_u16(temperature2, 8u, 0xffu);
    temperature3 = (uint16_t)src_p->temperature3;
    dst_p[13] |= pack_left_shift_u16(temperature3, 0u, 0xffu);
    dst_p[14] |= pack_right_shift_u16(temperature3, 8u, 0xffu);

    return (16);
}

int ucr_01_front_aero_unpack(
    struct ucr_01_front_aero_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint16_t temperature1;
    uint16_t temperature2;
    uint16_t temperature3;
    uint32_t pressure1;
    uint32_t pressure2;
    uint32_t pressure3;

    if (size < 16u) {
        return (-EINVAL);
    }

    pressure1 = unpack_right_shift_u32(src_p[0], 0u, 0xffu);
    pressure1 |= unpack_left_shift_u32(src_p[1], 8u, 0xffu);
    pressure1 |= unpack_left_shift_u32(src_p[2], 16u, 0xffu);

    if ((pressure1 & (1u << 23)) != 0u) {
        pressure1 |= 0xff000000u;
    }

    dst_p->pressure1 = (int32_t)pressure1;
    pressure2 = unpack_right_shift_u32(src_p[3], 0u, 0xffu);
    pressure2 |= unpack_left_shift_u32(src_p[4], 8u, 0xffu);
    pressure2 |= unpack_left_shift_u32(src_p[5], 16u, 0xffu);

    if ((pressure2 & (1u << 23)) != 0u) {
        pressure2 |= 0xff000000u;
    }

    dst_p->pressure2 = (int32_t)pressure2;
    pressure3 = unpack_right_shift_u32(src_p[6], 0u, 0xffu);
    pressure3 |= unpack_left_shift_u32(src_p[7], 8u, 0xffu);
    pressure3 |= unpack_left_shift_u32(src_p[8], 16u, 0xffu);

    if ((pressure3 & (1u << 23)) != 0u) {
        pressure3 |= 0xff000000u;
    }

    dst_p->pressure3 = (int32_t)pressure3;
    temperature1 = unpack_right_shift_u16(src_p[9], 0u, 0xffu);
    temperature1 |= unpack_left_shift_u16(src_p[10], 8u, 0xffu);
    dst_p->temperature1 = (int16_t)temperature1;
    temperature2 = unpack_right_shift_u16(src_p[11], 0u, 0xffu);
    temperature2 |= unpack_left_shift_u16(src_p[12], 8u, 0xffu);
    dst_p->temperature2 = (int16_t)temperature2;
    temperature3 = unpack_right_shift_u16(src_p[13], 0u, 0xffu);
    temperature3 |= unpack_left_shift_u16(src_p[14], 8u, 0xffu);
    dst_p->temperature3 = (int16_t)temperature3;

    return (0);
}

int ucr_01_front_aero_init(struct ucr_01_front_aero_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct ucr_01_front_aero_t));

    return 0;
}

int32_t ucr_01_front_aero_pressure1_encode(double value)
{
    return (int32_t)(value);
}

double ucr_01_front_aero_pressure1_decode(int32_t value)
{
    return ((double)value);
}

bool ucr_01_front_aero_pressure1_is_in_range(int32_t value)
{
    return ((value >= -8388608) && (value <= 8388607));
}

int32_t ucr_01_front_aero_pressure2_encode(double value)
{
    return (int32_t)(value);
}

double ucr_01_front_aero_pressure2_decode(int32_t value)
{
    return ((double)value);
}

bool ucr_01_front_aero_pressure2_is_in_range(int32_t value)
{
    return ((value >= -8388608) && (value <= 8388607));
}

int32_t ucr_01_front_aero_pressure3_encode(double value)
{
    return (int32_t)(value);
}

double ucr_01_front_aero_pressure3_decode(int32_t value)
{
    return ((double)value);
}

bool ucr_01_front_aero_pressure3_is_in_range(int32_t value)
{
    return ((value >= -8388608) && (value <= 8388607));
}

int16_t ucr_01_front_aero_temperature1_encode(double value)
{
    return (int16_t)(value);
}

double ucr_01_front_aero_temperature1_decode(int16_t value)
{
    return ((double)value);
}

bool ucr_01_front_aero_temperature1_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int16_t ucr_01_front_aero_temperature2_encode(double value)
{
    return (int16_t)(value);
}

double ucr_01_front_aero_temperature2_decode(int16_t value)
{
    return ((double)value);
}

bool ucr_01_front_aero_temperature2_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int16_t ucr_01_front_aero_temperature3_encode(double value)
{
    return (int16_t)(value);
}

double ucr_01_front_aero_temperature3_decode(int16_t value)
{
    return ((double)value);
}

bool ucr_01_front_aero_temperature3_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int ucr_01_rear_aero_pack(
    uint8_t *dst_p,
    const struct ucr_01_rear_aero_t *src_p,
    size_t size)
{
    uint16_t temperature1;
    uint16_t temperature2;
    uint16_t temperature3;
    uint32_t pressure1;
    uint32_t pressure2;
    uint32_t pressure3;

    if (size < 16u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 16);

    pressure1 = (uint32_t)src_p->pressure1;
    dst_p[0] |= pack_left_shift_u32(pressure1, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u32(pressure1, 8u, 0xffu);
    dst_p[2] |= pack_right_shift_u32(pressure1, 16u, 0xffu);
    pressure2 = (uint32_t)src_p->pressure2;
    dst_p[3] |= pack_left_shift_u32(pressure2, 0u, 0xffu);
    dst_p[4] |= pack_right_shift_u32(pressure2, 8u, 0xffu);
    dst_p[5] |= pack_right_shift_u32(pressure2, 16u, 0xffu);
    pressure3 = (uint32_t)src_p->pressure3;
    dst_p[6] |= pack_left_shift_u32(pressure3, 0u, 0xffu);
    dst_p[7] |= pack_right_shift_u32(pressure3, 8u, 0xffu);
    dst_p[8] |= pack_right_shift_u32(pressure3, 16u, 0xffu);
    temperature1 = (uint16_t)src_p->temperature1;
    dst_p[9] |= pack_left_shift_u16(temperature1, 0u, 0xffu);
    dst_p[10] |= pack_right_shift_u16(temperature1, 8u, 0xffu);
    temperature2 = (uint16_t)src_p->temperature2;
    dst_p[11] |= pack_left_shift_u16(temperature2, 0u, 0xffu);
    dst_p[12] |= pack_right_shift_u16(temperature2, 8u, 0xffu);
    temperature3 = (uint16_t)src_p->temperature3;
    dst_p[13] |= pack_left_shift_u16(temperature3, 0u, 0xffu);
    dst_p[14] |= pack_right_shift_u16(temperature3, 8u, 0xffu);

    return (16);
}

int ucr_01_rear_aero_unpack(
    struct ucr_01_rear_aero_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint16_t temperature1;
    uint16_t temperature2;
    uint16_t temperature3;
    uint32_t pressure1;
    uint32_t pressure2;
    uint32_t pressure3;

    if (size < 16u) {
        return (-EINVAL);
    }

    pressure1 = unpack_right_shift_u32(src_p[0], 0u, 0xffu);
    pressure1 |= unpack_left_shift_u32(src_p[1], 8u, 0xffu);
    pressure1 |= unpack_left_shift_u32(src_p[2], 16u, 0xffu);

    if ((pressure1 & (1u << 23)) != 0u) {
        pressure1 |= 0xff000000u;
    }

    dst_p->pressure1 = (int32_t)pressure1;
    pressure2 = unpack_right_shift_u32(src_p[3], 0u, 0xffu);
    pressure2 |= unpack_left_shift_u32(src_p[4], 8u, 0xffu);
    pressure2 |= unpack_left_shift_u32(src_p[5], 16u, 0xffu);

    if ((pressure2 & (1u << 23)) != 0u) {
        pressure2 |= 0xff000000u;
    }

    dst_p->pressure2 = (int32_t)pressure2;
    pressure3 = unpack_right_shift_u32(src_p[6], 0u, 0xffu);
    pressure3 |= unpack_left_shift_u32(src_p[7], 8u, 0xffu);
    pressure3 |= unpack_left_shift_u32(src_p[8], 16u, 0xffu);

    if ((pressure3 & (1u << 23)) != 0u) {
        pressure3 |= 0xff000000u;
    }

    dst_p->pressure3 = (int32_t)pressure3;
    temperature1 = unpack_right_shift_u16(src_p[9], 0u, 0xffu);
    temperature1 |= unpack_left_shift_u16(src_p[10], 8u, 0xffu);
    dst_p->temperature1 = (int16_t)temperature1;
    temperature2 = unpack_right_shift_u16(src_p[11], 0u, 0xffu);
    temperature2 |= unpack_left_shift_u16(src_p[12], 8u, 0xffu);
    dst_p->temperature2 = (int16_t)temperature2;
    temperature3 = unpack_right_shift_u16(src_p[13], 0u, 0xffu);
    temperature3 |= unpack_left_shift_u16(src_p[14], 8u, 0xffu);
    dst_p->temperature3 = (int16_t)temperature3;

    return (0);
}

int ucr_01_rear_aero_init(struct ucr_01_rear_aero_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct ucr_01_rear_aero_t));

    return 0;
}

int32_t ucr_01_rear_aero_pressure1_encode(double value)
{
    return (int32_t)(value);
}

double ucr_01_rear_aero_pressure1_decode(int32_t value)
{
    return ((double)value);
}

bool ucr_01_rear_aero_pressure1_is_in_range(int32_t value)
{
    return ((value >= -8388608) && (value <= 8388607));
}

int32_t ucr_01_rear_aero_pressure2_encode(double value)
{
    return (int32_t)(value);
}

double ucr_01_rear_aero_pressure2_decode(int32_t value)
{
    return ((double)value);
}

bool ucr_01_rear_aero_pressure2_is_in_range(int32_t value)
{
    return ((value >= -8388608) && (value <= 8388607));
}

int32_t ucr_01_rear_aero_pressure3_encode(double value)
{
    return (int32_t)(value);
}

double ucr_01_rear_aero_pressure3_decode(int32_t value)
{
    return ((double)value);
}

bool ucr_01_rear_aero_pressure3_is_in_range(int32_t value)
{
    return ((value >= -8388608) && (value <= 8388607));
}

int16_t ucr_01_rear_aero_temperature1_encode(double value)
{
    return (int16_t)(value);
}

double ucr_01_rear_aero_temperature1_decode(int16_t value)
{
    return ((double)value);
}

bool ucr_01_rear_aero_temperature1_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int16_t ucr_01_rear_aero_temperature2_encode(double value)
{
    return (int16_t)(value);
}

double ucr_01_rear_aero_temperature2_decode(int16_t value)
{
    return ((double)value);
}

bool ucr_01_rear_aero_temperature2_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int16_t ucr_01_rear_aero_temperature3_encode(double value)
{
    return (int16_t)(value);
}

double ucr_01_rear_aero_temperature3_decode(int16_t value)
{
    return ((double)value);
}

bool ucr_01_rear_aero_temperature3_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int ucr_01_encoder_positions_pack(
    uint8_t *dst_p,
    const struct ucr_01_encoder_positions_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u8(src_p->encoder1, 0u, 0xffu);
    dst_p[1] |= pack_left_shift_u8(src_p->encoder2, 0u, 0xffu);
    dst_p[2] |= pack_left_shift_u8(src_p->encoder3, 0u, 0xffu);
    dst_p[3] |= pack_left_shift_u8(src_p->encoder4, 0u, 0xffu);

    return (8);
}

int ucr_01_encoder_positions_unpack(
    struct ucr_01_encoder_positions_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->encoder1 = unpack_right_shift_u8(src_p[0], 0u, 0xffu);
    dst_p->encoder2 = unpack_right_shift_u8(src_p[1], 0u, 0xffu);
    dst_p->encoder3 = unpack_right_shift_u8(src_p[2], 0u, 0xffu);
    dst_p->encoder4 = unpack_right_shift_u8(src_p[3], 0u, 0xffu);

    return (0);
}

int ucr_01_encoder_positions_init(struct ucr_01_encoder_positions_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct ucr_01_encoder_positions_t));

    return 0;
}

uint8_t ucr_01_encoder_positions_encoder1_encode(double value)
{
    return (uint8_t)(value);
}

double ucr_01_encoder_positions_encoder1_decode(uint8_t value)
{
    return ((double)value);
}

bool ucr_01_encoder_positions_encoder1_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t ucr_01_encoder_positions_encoder2_encode(double value)
{
    return (uint8_t)(value);
}

double ucr_01_encoder_positions_encoder2_decode(uint8_t value)
{
    return ((double)value);
}

bool ucr_01_encoder_positions_encoder2_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t ucr_01_encoder_positions_encoder3_encode(double value)
{
    return (uint8_t)(value);
}

double ucr_01_encoder_positions_encoder3_decode(uint8_t value)
{
    return ((double)value);
}

bool ucr_01_encoder_positions_encoder3_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t ucr_01_encoder_positions_encoder4_encode(double value)
{
    return (uint8_t)(value);
}

double ucr_01_encoder_positions_encoder4_decode(uint8_t value)
{
    return ((double)value);
}

bool ucr_01_encoder_positions_encoder4_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

int ucr_01_front_strain_gauges1_pack(
    uint8_t *dst_p,
    const struct ucr_01_front_strain_gauges1_t *src_p,
    size_t size)
{
    if (size < 20u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 20);

    dst_p[0] |= pack_left_shift_u32(src_p->gauge1, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u32(src_p->gauge1, 8u, 0xffu);
    dst_p[2] |= pack_right_shift_u32(src_p->gauge1, 16u, 0xffu);
    dst_p[3] |= pack_left_shift_u32(src_p->gauge2, 0u, 0xffu);
    dst_p[4] |= pack_right_shift_u32(src_p->gauge2, 8u, 0xffu);
    dst_p[5] |= pack_right_shift_u32(src_p->gauge2, 16u, 0xffu);
    dst_p[6] |= pack_left_shift_u32(src_p->gauge3, 0u, 0xffu);
    dst_p[7] |= pack_right_shift_u32(src_p->gauge3, 8u, 0xffu);
    dst_p[8] |= pack_right_shift_u32(src_p->gauge3, 16u, 0xffu);
    dst_p[9] |= pack_left_shift_u32(src_p->gauge4, 0u, 0xffu);
    dst_p[10] |= pack_right_shift_u32(src_p->gauge4, 8u, 0xffu);
    dst_p[11] |= pack_right_shift_u32(src_p->gauge4, 16u, 0xffu);
    dst_p[12] |= pack_left_shift_u32(src_p->gauge5, 0u, 0xffu);
    dst_p[13] |= pack_right_shift_u32(src_p->gauge5, 8u, 0xffu);
    dst_p[14] |= pack_right_shift_u32(src_p->gauge5, 16u, 0xffu);
    dst_p[15] |= pack_left_shift_u32(src_p->gauge6, 0u, 0xffu);
    dst_p[16] |= pack_right_shift_u32(src_p->gauge6, 8u, 0xffu);
    dst_p[17] |= pack_right_shift_u32(src_p->gauge6, 16u, 0xffu);

    return (20);
}

int ucr_01_front_strain_gauges1_unpack(
    struct ucr_01_front_strain_gauges1_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 20u) {
        return (-EINVAL);
    }

    dst_p->gauge1 = unpack_right_shift_u32(src_p[0], 0u, 0xffu);
    dst_p->gauge1 |= unpack_left_shift_u32(src_p[1], 8u, 0xffu);
    dst_p->gauge1 |= unpack_left_shift_u32(src_p[2], 16u, 0xffu);
    dst_p->gauge2 = unpack_right_shift_u32(src_p[3], 0u, 0xffu);
    dst_p->gauge2 |= unpack_left_shift_u32(src_p[4], 8u, 0xffu);
    dst_p->gauge2 |= unpack_left_shift_u32(src_p[5], 16u, 0xffu);
    dst_p->gauge3 = unpack_right_shift_u32(src_p[6], 0u, 0xffu);
    dst_p->gauge3 |= unpack_left_shift_u32(src_p[7], 8u, 0xffu);
    dst_p->gauge3 |= unpack_left_shift_u32(src_p[8], 16u, 0xffu);
    dst_p->gauge4 = unpack_right_shift_u32(src_p[9], 0u, 0xffu);
    dst_p->gauge4 |= unpack_left_shift_u32(src_p[10], 8u, 0xffu);
    dst_p->gauge4 |= unpack_left_shift_u32(src_p[11], 16u, 0xffu);
    dst_p->gauge5 = unpack_right_shift_u32(src_p[12], 0u, 0xffu);
    dst_p->gauge5 |= unpack_left_shift_u32(src_p[13], 8u, 0xffu);
    dst_p->gauge5 |= unpack_left_shift_u32(src_p[14], 16u, 0xffu);
    dst_p->gauge6 = unpack_right_shift_u32(src_p[15], 0u, 0xffu);
    dst_p->gauge6 |= unpack_left_shift_u32(src_p[16], 8u, 0xffu);
    dst_p->gauge6 |= unpack_left_shift_u32(src_p[17], 16u, 0xffu);

    return (0);
}

int ucr_01_front_strain_gauges1_init(struct ucr_01_front_strain_gauges1_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct ucr_01_front_strain_gauges1_t));

    return 0;
}

uint32_t ucr_01_front_strain_gauges1_gauge1_encode(double value)
{
    return (uint32_t)(value);
}

double ucr_01_front_strain_gauges1_gauge1_decode(uint32_t value)
{
    return ((double)value);
}

bool ucr_01_front_strain_gauges1_gauge1_is_in_range(uint32_t value)
{
    return (value <= 16777215u);
}

uint32_t ucr_01_front_strain_gauges1_gauge2_encode(double value)
{
    return (uint32_t)(value);
}

double ucr_01_front_strain_gauges1_gauge2_decode(uint32_t value)
{
    return ((double)value);
}

bool ucr_01_front_strain_gauges1_gauge2_is_in_range(uint32_t value)
{
    return (value <= 16777215u);
}

uint32_t ucr_01_front_strain_gauges1_gauge3_encode(double value)
{
    return (uint32_t)(value);
}

double ucr_01_front_strain_gauges1_gauge3_decode(uint32_t value)
{
    return ((double)value);
}

bool ucr_01_front_strain_gauges1_gauge3_is_in_range(uint32_t value)
{
    return (value <= 16777215u);
}

uint32_t ucr_01_front_strain_gauges1_gauge4_encode(double value)
{
    return (uint32_t)(value);
}

double ucr_01_front_strain_gauges1_gauge4_decode(uint32_t value)
{
    return ((double)value);
}

bool ucr_01_front_strain_gauges1_gauge4_is_in_range(uint32_t value)
{
    return (value <= 16777215u);
}

uint32_t ucr_01_front_strain_gauges1_gauge5_encode(double value)
{
    return (uint32_t)(value);
}

double ucr_01_front_strain_gauges1_gauge5_decode(uint32_t value)
{
    return ((double)value);
}

bool ucr_01_front_strain_gauges1_gauge5_is_in_range(uint32_t value)
{
    return (value <= 16777215u);
}

uint32_t ucr_01_front_strain_gauges1_gauge6_encode(double value)
{
    return (uint32_t)(value);
}

double ucr_01_front_strain_gauges1_gauge6_decode(uint32_t value)
{
    return ((double)value);
}

bool ucr_01_front_strain_gauges1_gauge6_is_in_range(uint32_t value)
{
    return (value <= 16777215u);
}

int ucr_01_front_strain_gauges2_pack(
    uint8_t *dst_p,
    const struct ucr_01_front_strain_gauges2_t *src_p,
    size_t size)
{
    if (size < 20u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 20);

    dst_p[0] |= pack_left_shift_u32(src_p->gauge1, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u32(src_p->gauge1, 8u, 0xffu);
    dst_p[2] |= pack_right_shift_u32(src_p->gauge1, 16u, 0xffu);
    dst_p[3] |= pack_left_shift_u32(src_p->gauge2, 0u, 0xffu);
    dst_p[4] |= pack_right_shift_u32(src_p->gauge2, 8u, 0xffu);
    dst_p[5] |= pack_right_shift_u32(src_p->gauge2, 16u, 0xffu);
    dst_p[6] |= pack_left_shift_u32(src_p->gauge3, 0u, 0xffu);
    dst_p[7] |= pack_right_shift_u32(src_p->gauge3, 8u, 0xffu);
    dst_p[8] |= pack_right_shift_u32(src_p->gauge3, 16u, 0xffu);
    dst_p[9] |= pack_left_shift_u32(src_p->gauge4, 0u, 0xffu);
    dst_p[10] |= pack_right_shift_u32(src_p->gauge4, 8u, 0xffu);
    dst_p[11] |= pack_right_shift_u32(src_p->gauge4, 16u, 0xffu);
    dst_p[12] |= pack_left_shift_u32(src_p->gauge5, 0u, 0xffu);
    dst_p[13] |= pack_right_shift_u32(src_p->gauge5, 8u, 0xffu);
    dst_p[14] |= pack_right_shift_u32(src_p->gauge5, 16u, 0xffu);
    dst_p[15] |= pack_left_shift_u32(src_p->gauge6, 0u, 0xffu);
    dst_p[16] |= pack_right_shift_u32(src_p->gauge6, 8u, 0xffu);
    dst_p[17] |= pack_right_shift_u32(src_p->gauge6, 16u, 0xffu);

    return (20);
}

int ucr_01_front_strain_gauges2_unpack(
    struct ucr_01_front_strain_gauges2_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 20u) {
        return (-EINVAL);
    }

    dst_p->gauge1 = unpack_right_shift_u32(src_p[0], 0u, 0xffu);
    dst_p->gauge1 |= unpack_left_shift_u32(src_p[1], 8u, 0xffu);
    dst_p->gauge1 |= unpack_left_shift_u32(src_p[2], 16u, 0xffu);
    dst_p->gauge2 = unpack_right_shift_u32(src_p[3], 0u, 0xffu);
    dst_p->gauge2 |= unpack_left_shift_u32(src_p[4], 8u, 0xffu);
    dst_p->gauge2 |= unpack_left_shift_u32(src_p[5], 16u, 0xffu);
    dst_p->gauge3 = unpack_right_shift_u32(src_p[6], 0u, 0xffu);
    dst_p->gauge3 |= unpack_left_shift_u32(src_p[7], 8u, 0xffu);
    dst_p->gauge3 |= unpack_left_shift_u32(src_p[8], 16u, 0xffu);
    dst_p->gauge4 = unpack_right_shift_u32(src_p[9], 0u, 0xffu);
    dst_p->gauge4 |= unpack_left_shift_u32(src_p[10], 8u, 0xffu);
    dst_p->gauge4 |= unpack_left_shift_u32(src_p[11], 16u, 0xffu);
    dst_p->gauge5 = unpack_right_shift_u32(src_p[12], 0u, 0xffu);
    dst_p->gauge5 |= unpack_left_shift_u32(src_p[13], 8u, 0xffu);
    dst_p->gauge5 |= unpack_left_shift_u32(src_p[14], 16u, 0xffu);
    dst_p->gauge6 = unpack_right_shift_u32(src_p[15], 0u, 0xffu);
    dst_p->gauge6 |= unpack_left_shift_u32(src_p[16], 8u, 0xffu);
    dst_p->gauge6 |= unpack_left_shift_u32(src_p[17], 16u, 0xffu);

    return (0);
}

int ucr_01_front_strain_gauges2_init(struct ucr_01_front_strain_gauges2_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct ucr_01_front_strain_gauges2_t));

    return 0;
}

uint32_t ucr_01_front_strain_gauges2_gauge1_encode(double value)
{
    return (uint32_t)(value);
}

double ucr_01_front_strain_gauges2_gauge1_decode(uint32_t value)
{
    return ((double)value);
}

bool ucr_01_front_strain_gauges2_gauge1_is_in_range(uint32_t value)
{
    return (value <= 16777215u);
}

uint32_t ucr_01_front_strain_gauges2_gauge2_encode(double value)
{
    return (uint32_t)(value);
}

double ucr_01_front_strain_gauges2_gauge2_decode(uint32_t value)
{
    return ((double)value);
}

bool ucr_01_front_strain_gauges2_gauge2_is_in_range(uint32_t value)
{
    return (value <= 16777215u);
}

uint32_t ucr_01_front_strain_gauges2_gauge3_encode(double value)
{
    return (uint32_t)(value);
}

double ucr_01_front_strain_gauges2_gauge3_decode(uint32_t value)
{
    return ((double)value);
}

bool ucr_01_front_strain_gauges2_gauge3_is_in_range(uint32_t value)
{
    return (value <= 16777215u);
}

uint32_t ucr_01_front_strain_gauges2_gauge4_encode(double value)
{
    return (uint32_t)(value);
}

double ucr_01_front_strain_gauges2_gauge4_decode(uint32_t value)
{
    return ((double)value);
}

bool ucr_01_front_strain_gauges2_gauge4_is_in_range(uint32_t value)
{
    return (value <= 16777215u);
}

uint32_t ucr_01_front_strain_gauges2_gauge5_encode(double value)
{
    return (uint32_t)(value);
}

double ucr_01_front_strain_gauges2_gauge5_decode(uint32_t value)
{
    return ((double)value);
}

bool ucr_01_front_strain_gauges2_gauge5_is_in_range(uint32_t value)
{
    return (value <= 16777215u);
}

uint32_t ucr_01_front_strain_gauges2_gauge6_encode(double value)
{
    return (uint32_t)(value);
}

double ucr_01_front_strain_gauges2_gauge6_decode(uint32_t value)
{
    return ((double)value);
}

bool ucr_01_front_strain_gauges2_gauge6_is_in_range(uint32_t value)
{
    return (value <= 16777215u);
}

int ucr_01_rear_strain_gauges1_pack(
    uint8_t *dst_p,
    const struct ucr_01_rear_strain_gauges1_t *src_p,
    size_t size)
{
    if (size < 20u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 20);

    dst_p[0] |= pack_left_shift_u32(src_p->gauge1, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u32(src_p->gauge1, 8u, 0xffu);
    dst_p[2] |= pack_right_shift_u32(src_p->gauge1, 16u, 0xffu);
    dst_p[3] |= pack_left_shift_u32(src_p->gauge2, 0u, 0xffu);
    dst_p[4] |= pack_right_shift_u32(src_p->gauge2, 8u, 0xffu);
    dst_p[5] |= pack_right_shift_u32(src_p->gauge2, 16u, 0xffu);
    dst_p[6] |= pack_left_shift_u32(src_p->gauge3, 0u, 0xffu);
    dst_p[7] |= pack_right_shift_u32(src_p->gauge3, 8u, 0xffu);
    dst_p[8] |= pack_right_shift_u32(src_p->gauge3, 16u, 0xffu);
    dst_p[9] |= pack_left_shift_u32(src_p->gauge4, 0u, 0xffu);
    dst_p[10] |= pack_right_shift_u32(src_p->gauge4, 8u, 0xffu);
    dst_p[11] |= pack_right_shift_u32(src_p->gauge4, 16u, 0xffu);
    dst_p[12] |= pack_left_shift_u32(src_p->gauge5, 0u, 0xffu);
    dst_p[13] |= pack_right_shift_u32(src_p->gauge5, 8u, 0xffu);
    dst_p[14] |= pack_right_shift_u32(src_p->gauge5, 16u, 0xffu);
    dst_p[15] |= pack_left_shift_u32(src_p->gauge6, 0u, 0xffu);
    dst_p[16] |= pack_right_shift_u32(src_p->gauge6, 8u, 0xffu);
    dst_p[17] |= pack_right_shift_u32(src_p->gauge6, 16u, 0xffu);

    return (20);
}

int ucr_01_rear_strain_gauges1_unpack(
    struct ucr_01_rear_strain_gauges1_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 20u) {
        return (-EINVAL);
    }

    dst_p->gauge1 = unpack_right_shift_u32(src_p[0], 0u, 0xffu);
    dst_p->gauge1 |= unpack_left_shift_u32(src_p[1], 8u, 0xffu);
    dst_p->gauge1 |= unpack_left_shift_u32(src_p[2], 16u, 0xffu);
    dst_p->gauge2 = unpack_right_shift_u32(src_p[3], 0u, 0xffu);
    dst_p->gauge2 |= unpack_left_shift_u32(src_p[4], 8u, 0xffu);
    dst_p->gauge2 |= unpack_left_shift_u32(src_p[5], 16u, 0xffu);
    dst_p->gauge3 = unpack_right_shift_u32(src_p[6], 0u, 0xffu);
    dst_p->gauge3 |= unpack_left_shift_u32(src_p[7], 8u, 0xffu);
    dst_p->gauge3 |= unpack_left_shift_u32(src_p[8], 16u, 0xffu);
    dst_p->gauge4 = unpack_right_shift_u32(src_p[9], 0u, 0xffu);
    dst_p->gauge4 |= unpack_left_shift_u32(src_p[10], 8u, 0xffu);
    dst_p->gauge4 |= unpack_left_shift_u32(src_p[11], 16u, 0xffu);
    dst_p->gauge5 = unpack_right_shift_u32(src_p[12], 0u, 0xffu);
    dst_p->gauge5 |= unpack_left_shift_u32(src_p[13], 8u, 0xffu);
    dst_p->gauge5 |= unpack_left_shift_u32(src_p[14], 16u, 0xffu);
    dst_p->gauge6 = unpack_right_shift_u32(src_p[15], 0u, 0xffu);
    dst_p->gauge6 |= unpack_left_shift_u32(src_p[16], 8u, 0xffu);
    dst_p->gauge6 |= unpack_left_shift_u32(src_p[17], 16u, 0xffu);

    return (0);
}

int ucr_01_rear_strain_gauges1_init(struct ucr_01_rear_strain_gauges1_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct ucr_01_rear_strain_gauges1_t));

    return 0;
}

uint32_t ucr_01_rear_strain_gauges1_gauge1_encode(double value)
{
    return (uint32_t)(value);
}

double ucr_01_rear_strain_gauges1_gauge1_decode(uint32_t value)
{
    return ((double)value);
}

bool ucr_01_rear_strain_gauges1_gauge1_is_in_range(uint32_t value)
{
    return (value <= 16777215u);
}

uint32_t ucr_01_rear_strain_gauges1_gauge2_encode(double value)
{
    return (uint32_t)(value);
}

double ucr_01_rear_strain_gauges1_gauge2_decode(uint32_t value)
{
    return ((double)value);
}

bool ucr_01_rear_strain_gauges1_gauge2_is_in_range(uint32_t value)
{
    return (value <= 16777215u);
}

uint32_t ucr_01_rear_strain_gauges1_gauge3_encode(double value)
{
    return (uint32_t)(value);
}

double ucr_01_rear_strain_gauges1_gauge3_decode(uint32_t value)
{
    return ((double)value);
}

bool ucr_01_rear_strain_gauges1_gauge3_is_in_range(uint32_t value)
{
    return (value <= 16777215u);
}

uint32_t ucr_01_rear_strain_gauges1_gauge4_encode(double value)
{
    return (uint32_t)(value);
}

double ucr_01_rear_strain_gauges1_gauge4_decode(uint32_t value)
{
    return ((double)value);
}

bool ucr_01_rear_strain_gauges1_gauge4_is_in_range(uint32_t value)
{
    return (value <= 16777215u);
}

uint32_t ucr_01_rear_strain_gauges1_gauge5_encode(double value)
{
    return (uint32_t)(value);
}

double ucr_01_rear_strain_gauges1_gauge5_decode(uint32_t value)
{
    return ((double)value);
}

bool ucr_01_rear_strain_gauges1_gauge5_is_in_range(uint32_t value)
{
    return (value <= 16777215u);
}

uint32_t ucr_01_rear_strain_gauges1_gauge6_encode(double value)
{
    return (uint32_t)(value);
}

double ucr_01_rear_strain_gauges1_gauge6_decode(uint32_t value)
{
    return ((double)value);
}

bool ucr_01_rear_strain_gauges1_gauge6_is_in_range(uint32_t value)
{
    return (value <= 16777215u);
}

int ucr_01_rear_strain_gauges2_pack(
    uint8_t *dst_p,
    const struct ucr_01_rear_strain_gauges2_t *src_p,
    size_t size)
{
    if (size < 20u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 20);

    dst_p[0] |= pack_left_shift_u32(src_p->gauge1, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u32(src_p->gauge1, 8u, 0xffu);
    dst_p[2] |= pack_right_shift_u32(src_p->gauge1, 16u, 0xffu);
    dst_p[3] |= pack_left_shift_u32(src_p->gauge2, 0u, 0xffu);
    dst_p[4] |= pack_right_shift_u32(src_p->gauge2, 8u, 0xffu);
    dst_p[5] |= pack_right_shift_u32(src_p->gauge2, 16u, 0xffu);
    dst_p[6] |= pack_left_shift_u32(src_p->gauge3, 0u, 0xffu);
    dst_p[7] |= pack_right_shift_u32(src_p->gauge3, 8u, 0xffu);
    dst_p[8] |= pack_right_shift_u32(src_p->gauge3, 16u, 0xffu);
    dst_p[9] |= pack_left_shift_u32(src_p->gauge4, 0u, 0xffu);
    dst_p[10] |= pack_right_shift_u32(src_p->gauge4, 8u, 0xffu);
    dst_p[11] |= pack_right_shift_u32(src_p->gauge4, 16u, 0xffu);
    dst_p[12] |= pack_left_shift_u32(src_p->gauge5, 0u, 0xffu);
    dst_p[13] |= pack_right_shift_u32(src_p->gauge5, 8u, 0xffu);
    dst_p[14] |= pack_right_shift_u32(src_p->gauge5, 16u, 0xffu);
    dst_p[15] |= pack_left_shift_u32(src_p->gauge6, 0u, 0xffu);
    dst_p[16] |= pack_right_shift_u32(src_p->gauge6, 8u, 0xffu);
    dst_p[17] |= pack_right_shift_u32(src_p->gauge6, 16u, 0xffu);

    return (20);
}

int ucr_01_rear_strain_gauges2_unpack(
    struct ucr_01_rear_strain_gauges2_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 20u) {
        return (-EINVAL);
    }

    dst_p->gauge1 = unpack_right_shift_u32(src_p[0], 0u, 0xffu);
    dst_p->gauge1 |= unpack_left_shift_u32(src_p[1], 8u, 0xffu);
    dst_p->gauge1 |= unpack_left_shift_u32(src_p[2], 16u, 0xffu);
    dst_p->gauge2 = unpack_right_shift_u32(src_p[3], 0u, 0xffu);
    dst_p->gauge2 |= unpack_left_shift_u32(src_p[4], 8u, 0xffu);
    dst_p->gauge2 |= unpack_left_shift_u32(src_p[5], 16u, 0xffu);
    dst_p->gauge3 = unpack_right_shift_u32(src_p[6], 0u, 0xffu);
    dst_p->gauge3 |= unpack_left_shift_u32(src_p[7], 8u, 0xffu);
    dst_p->gauge3 |= unpack_left_shift_u32(src_p[8], 16u, 0xffu);
    dst_p->gauge4 = unpack_right_shift_u32(src_p[9], 0u, 0xffu);
    dst_p->gauge4 |= unpack_left_shift_u32(src_p[10], 8u, 0xffu);
    dst_p->gauge4 |= unpack_left_shift_u32(src_p[11], 16u, 0xffu);
    dst_p->gauge5 = unpack_right_shift_u32(src_p[12], 0u, 0xffu);
    dst_p->gauge5 |= unpack_left_shift_u32(src_p[13], 8u, 0xffu);
    dst_p->gauge5 |= unpack_left_shift_u32(src_p[14], 16u, 0xffu);
    dst_p->gauge6 = unpack_right_shift_u32(src_p[15], 0u, 0xffu);
    dst_p->gauge6 |= unpack_left_shift_u32(src_p[16], 8u, 0xffu);
    dst_p->gauge6 |= unpack_left_shift_u32(src_p[17], 16u, 0xffu);

    return (0);
}

int ucr_01_rear_strain_gauges2_init(struct ucr_01_rear_strain_gauges2_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct ucr_01_rear_strain_gauges2_t));

    return 0;
}

uint32_t ucr_01_rear_strain_gauges2_gauge1_encode(double value)
{
    return (uint32_t)(value);
}

double ucr_01_rear_strain_gauges2_gauge1_decode(uint32_t value)
{
    return ((double)value);
}

bool ucr_01_rear_strain_gauges2_gauge1_is_in_range(uint32_t value)
{
    return (value <= 16777215u);
}

uint32_t ucr_01_rear_strain_gauges2_gauge2_encode(double value)
{
    return (uint32_t)(value);
}

double ucr_01_rear_strain_gauges2_gauge2_decode(uint32_t value)
{
    return ((double)value);
}

bool ucr_01_rear_strain_gauges2_gauge2_is_in_range(uint32_t value)
{
    return (value <= 16777215u);
}

uint32_t ucr_01_rear_strain_gauges2_gauge3_encode(double value)
{
    return (uint32_t)(value);
}

double ucr_01_rear_strain_gauges2_gauge3_decode(uint32_t value)
{
    return ((double)value);
}

bool ucr_01_rear_strain_gauges2_gauge3_is_in_range(uint32_t value)
{
    return (value <= 16777215u);
}

uint32_t ucr_01_rear_strain_gauges2_gauge4_encode(double value)
{
    return (uint32_t)(value);
}

double ucr_01_rear_strain_gauges2_gauge4_decode(uint32_t value)
{
    return ((double)value);
}

bool ucr_01_rear_strain_gauges2_gauge4_is_in_range(uint32_t value)
{
    return (value <= 16777215u);
}

uint32_t ucr_01_rear_strain_gauges2_gauge5_encode(double value)
{
    return (uint32_t)(value);
}

double ucr_01_rear_strain_gauges2_gauge5_decode(uint32_t value)
{
    return ((double)value);
}

bool ucr_01_rear_strain_gauges2_gauge5_is_in_range(uint32_t value)
{
    return (value <= 16777215u);
}

uint32_t ucr_01_rear_strain_gauges2_gauge6_encode(double value)
{
    return (uint32_t)(value);
}

double ucr_01_rear_strain_gauges2_gauge6_decode(uint32_t value)
{
    return ((double)value);
}

bool ucr_01_rear_strain_gauges2_gauge6_is_in_range(uint32_t value)
{
    return (value <= 16777215u);
}

int ucr_01_gps_best_pos_pack(
    uint8_t *dst_p,
    const struct ucr_01_gps_best_pos_t *src_p,
    size_t size)
{
    if (size < 64u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 64);

    dst_p[0] |= pack_left_shift_u32(src_p->new_signal_0001, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u32(src_p->new_signal_0001, 8u, 0xffu);
    dst_p[2] |= pack_right_shift_u32(src_p->new_signal_0001, 16u, 0xffu);
    dst_p[3] |= pack_right_shift_u32(src_p->new_signal_0001, 24u, 0xffu);

    return (64);
}

int ucr_01_gps_best_pos_unpack(
    struct ucr_01_gps_best_pos_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 64u) {
        return (-EINVAL);
    }

    dst_p->new_signal_0001 = unpack_right_shift_u32(src_p[0], 0u, 0xffu);
    dst_p->new_signal_0001 |= unpack_left_shift_u32(src_p[1], 8u, 0xffu);
    dst_p->new_signal_0001 |= unpack_left_shift_u32(src_p[2], 16u, 0xffu);
    dst_p->new_signal_0001 |= unpack_left_shift_u32(src_p[3], 24u, 0xffu);

    return (0);
}

int ucr_01_gps_best_pos_init(struct ucr_01_gps_best_pos_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct ucr_01_gps_best_pos_t));

    return 0;
}

uint32_t ucr_01_gps_best_pos_new_signal_0001_encode(double value)
{
    return (uint32_t)(value);
}

double ucr_01_gps_best_pos_new_signal_0001_decode(uint32_t value)
{
    return ((double)value);
}

bool ucr_01_gps_best_pos_new_signal_0001_is_in_range(uint32_t value)
{
    (void)value;

    return (true);
}

int ucr_01_front_frequency_pack(
    uint8_t *dst_p,
    const struct ucr_01_front_frequency_t *src_p,
    size_t size)
{
    uint32_t freq1;
    uint32_t freq2;
    uint32_t freq3;
    uint32_t freq4;

    if (size < 16u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 16);

    memcpy(&freq1, &src_p->freq1, sizeof(freq1));
    dst_p[0] |= pack_left_shift_u32(freq1, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u32(freq1, 8u, 0xffu);
    dst_p[2] |= pack_right_shift_u32(freq1, 16u, 0xffu);
    dst_p[3] |= pack_right_shift_u32(freq1, 24u, 0xffu);
    memcpy(&freq2, &src_p->freq2, sizeof(freq2));
    dst_p[4] |= pack_left_shift_u32(freq2, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u32(freq2, 8u, 0xffu);
    dst_p[6] |= pack_right_shift_u32(freq2, 16u, 0xffu);
    dst_p[7] |= pack_right_shift_u32(freq2, 24u, 0xffu);
    memcpy(&freq3, &src_p->freq3, sizeof(freq3));
    dst_p[8] |= pack_left_shift_u32(freq3, 0u, 0xffu);
    dst_p[9] |= pack_right_shift_u32(freq3, 8u, 0xffu);
    dst_p[10] |= pack_right_shift_u32(freq3, 16u, 0xffu);
    dst_p[11] |= pack_right_shift_u32(freq3, 24u, 0xffu);
    memcpy(&freq4, &src_p->freq4, sizeof(freq4));
    dst_p[12] |= pack_left_shift_u32(freq4, 0u, 0xffu);
    dst_p[13] |= pack_right_shift_u32(freq4, 8u, 0xffu);
    dst_p[14] |= pack_right_shift_u32(freq4, 16u, 0xffu);
    dst_p[15] |= pack_right_shift_u32(freq4, 24u, 0xffu);

    return (16);
}

int ucr_01_front_frequency_unpack(
    struct ucr_01_front_frequency_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint32_t freq1;
    uint32_t freq2;
    uint32_t freq3;
    uint32_t freq4;

    if (size < 16u) {
        return (-EINVAL);
    }

    freq1 = unpack_right_shift_u32(src_p[0], 0u, 0xffu);
    freq1 |= unpack_left_shift_u32(src_p[1], 8u, 0xffu);
    freq1 |= unpack_left_shift_u32(src_p[2], 16u, 0xffu);
    freq1 |= unpack_left_shift_u32(src_p[3], 24u, 0xffu);
    memcpy(&dst_p->freq1, &freq1, sizeof(dst_p->freq1));
    freq2 = unpack_right_shift_u32(src_p[4], 0u, 0xffu);
    freq2 |= unpack_left_shift_u32(src_p[5], 8u, 0xffu);
    freq2 |= unpack_left_shift_u32(src_p[6], 16u, 0xffu);
    freq2 |= unpack_left_shift_u32(src_p[7], 24u, 0xffu);
    memcpy(&dst_p->freq2, &freq2, sizeof(dst_p->freq2));
    freq3 = unpack_right_shift_u32(src_p[8], 0u, 0xffu);
    freq3 |= unpack_left_shift_u32(src_p[9], 8u, 0xffu);
    freq3 |= unpack_left_shift_u32(src_p[10], 16u, 0xffu);
    freq3 |= unpack_left_shift_u32(src_p[11], 24u, 0xffu);
    memcpy(&dst_p->freq3, &freq3, sizeof(dst_p->freq3));
    freq4 = unpack_right_shift_u32(src_p[12], 0u, 0xffu);
    freq4 |= unpack_left_shift_u32(src_p[13], 8u, 0xffu);
    freq4 |= unpack_left_shift_u32(src_p[14], 16u, 0xffu);
    freq4 |= unpack_left_shift_u32(src_p[15], 24u, 0xffu);
    memcpy(&dst_p->freq4, &freq4, sizeof(dst_p->freq4));

    return (0);
}

int ucr_01_front_frequency_init(struct ucr_01_front_frequency_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct ucr_01_front_frequency_t));

    return 0;
}

float ucr_01_front_frequency_freq1_encode(double value)
{
    return (float)(value);
}

double ucr_01_front_frequency_freq1_decode(float value)
{
    return ((double)value);
}

bool ucr_01_front_frequency_freq1_is_in_range(float value)
{
    (void)value;

    return (true);
}

float ucr_01_front_frequency_freq2_encode(double value)
{
    return (float)(value);
}

double ucr_01_front_frequency_freq2_decode(float value)
{
    return ((double)value);
}

bool ucr_01_front_frequency_freq2_is_in_range(float value)
{
    (void)value;

    return (true);
}

float ucr_01_front_frequency_freq3_encode(double value)
{
    return (float)(value);
}

double ucr_01_front_frequency_freq3_decode(float value)
{
    return ((double)value);
}

bool ucr_01_front_frequency_freq3_is_in_range(float value)
{
    (void)value;

    return (true);
}

float ucr_01_front_frequency_freq4_encode(double value)
{
    return (float)(value);
}

double ucr_01_front_frequency_freq4_decode(float value)
{
    return ((double)value);
}

bool ucr_01_front_frequency_freq4_is_in_range(float value)
{
    (void)value;

    return (true);
}

int ucr_01_rear_frequency_pack(
    uint8_t *dst_p,
    const struct ucr_01_rear_frequency_t *src_p,
    size_t size)
{
    uint64_t freq1;
    uint64_t freq2;
    uint64_t freq3;
    uint64_t freq4;

    if (size < 32u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 32);

    memcpy(&freq1, &src_p->freq1, sizeof(freq1));
    dst_p[0] |= pack_left_shift_u64(freq1, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u64(freq1, 8u, 0xffu);
    dst_p[2] |= pack_right_shift_u64(freq1, 16u, 0xffu);
    dst_p[3] |= pack_right_shift_u64(freq1, 24u, 0xffu);
    dst_p[4] |= pack_right_shift_u64(freq1, 32u, 0xffu);
    dst_p[5] |= pack_right_shift_u64(freq1, 40u, 0xffu);
    dst_p[6] |= pack_right_shift_u64(freq1, 48u, 0xffu);
    dst_p[7] |= pack_right_shift_u64(freq1, 56u, 0xffu);
    memcpy(&freq2, &src_p->freq2, sizeof(freq2));
    dst_p[8] |= pack_left_shift_u64(freq2, 0u, 0xffu);
    dst_p[9] |= pack_right_shift_u64(freq2, 8u, 0xffu);
    dst_p[10] |= pack_right_shift_u64(freq2, 16u, 0xffu);
    dst_p[11] |= pack_right_shift_u64(freq2, 24u, 0xffu);
    dst_p[12] |= pack_right_shift_u64(freq2, 32u, 0xffu);
    dst_p[13] |= pack_right_shift_u64(freq2, 40u, 0xffu);
    dst_p[14] |= pack_right_shift_u64(freq2, 48u, 0xffu);
    dst_p[15] |= pack_right_shift_u64(freq2, 56u, 0xffu);
    memcpy(&freq3, &src_p->freq3, sizeof(freq3));
    dst_p[16] |= pack_left_shift_u64(freq3, 0u, 0xffu);
    dst_p[17] |= pack_right_shift_u64(freq3, 8u, 0xffu);
    dst_p[18] |= pack_right_shift_u64(freq3, 16u, 0xffu);
    dst_p[19] |= pack_right_shift_u64(freq3, 24u, 0xffu);
    dst_p[20] |= pack_right_shift_u64(freq3, 32u, 0xffu);
    dst_p[21] |= pack_right_shift_u64(freq3, 40u, 0xffu);
    dst_p[22] |= pack_right_shift_u64(freq3, 48u, 0xffu);
    dst_p[23] |= pack_right_shift_u64(freq3, 56u, 0xffu);
    memcpy(&freq4, &src_p->freq4, sizeof(freq4));
    dst_p[24] |= pack_left_shift_u64(freq4, 0u, 0xffu);
    dst_p[25] |= pack_right_shift_u64(freq4, 8u, 0xffu);
    dst_p[26] |= pack_right_shift_u64(freq4, 16u, 0xffu);
    dst_p[27] |= pack_right_shift_u64(freq4, 24u, 0xffu);
    dst_p[28] |= pack_right_shift_u64(freq4, 32u, 0xffu);
    dst_p[29] |= pack_right_shift_u64(freq4, 40u, 0xffu);
    dst_p[30] |= pack_right_shift_u64(freq4, 48u, 0xffu);
    dst_p[31] |= pack_right_shift_u64(freq4, 56u, 0xffu);

    return (32);
}

int ucr_01_rear_frequency_unpack(
    struct ucr_01_rear_frequency_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint64_t freq1;
    uint64_t freq2;
    uint64_t freq3;
    uint64_t freq4;

    if (size < 32u) {
        return (-EINVAL);
    }

    freq1 = unpack_right_shift_u64(src_p[0], 0u, 0xffu);
    freq1 |= unpack_left_shift_u64(src_p[1], 8u, 0xffu);
    freq1 |= unpack_left_shift_u64(src_p[2], 16u, 0xffu);
    freq1 |= unpack_left_shift_u64(src_p[3], 24u, 0xffu);
    freq1 |= unpack_left_shift_u64(src_p[4], 32u, 0xffu);
    freq1 |= unpack_left_shift_u64(src_p[5], 40u, 0xffu);
    freq1 |= unpack_left_shift_u64(src_p[6], 48u, 0xffu);
    freq1 |= unpack_left_shift_u64(src_p[7], 56u, 0xffu);
    memcpy(&dst_p->freq1, &freq1, sizeof(dst_p->freq1));
    freq2 = unpack_right_shift_u64(src_p[8], 0u, 0xffu);
    freq2 |= unpack_left_shift_u64(src_p[9], 8u, 0xffu);
    freq2 |= unpack_left_shift_u64(src_p[10], 16u, 0xffu);
    freq2 |= unpack_left_shift_u64(src_p[11], 24u, 0xffu);
    freq2 |= unpack_left_shift_u64(src_p[12], 32u, 0xffu);
    freq2 |= unpack_left_shift_u64(src_p[13], 40u, 0xffu);
    freq2 |= unpack_left_shift_u64(src_p[14], 48u, 0xffu);
    freq2 |= unpack_left_shift_u64(src_p[15], 56u, 0xffu);
    memcpy(&dst_p->freq2, &freq2, sizeof(dst_p->freq2));
    freq3 = unpack_right_shift_u64(src_p[16], 0u, 0xffu);
    freq3 |= unpack_left_shift_u64(src_p[17], 8u, 0xffu);
    freq3 |= unpack_left_shift_u64(src_p[18], 16u, 0xffu);
    freq3 |= unpack_left_shift_u64(src_p[19], 24u, 0xffu);
    freq3 |= unpack_left_shift_u64(src_p[20], 32u, 0xffu);
    freq3 |= unpack_left_shift_u64(src_p[21], 40u, 0xffu);
    freq3 |= unpack_left_shift_u64(src_p[22], 48u, 0xffu);
    freq3 |= unpack_left_shift_u64(src_p[23], 56u, 0xffu);
    memcpy(&dst_p->freq3, &freq3, sizeof(dst_p->freq3));
    freq4 = unpack_right_shift_u64(src_p[24], 0u, 0xffu);
    freq4 |= unpack_left_shift_u64(src_p[25], 8u, 0xffu);
    freq4 |= unpack_left_shift_u64(src_p[26], 16u, 0xffu);
    freq4 |= unpack_left_shift_u64(src_p[27], 24u, 0xffu);
    freq4 |= unpack_left_shift_u64(src_p[28], 32u, 0xffu);
    freq4 |= unpack_left_shift_u64(src_p[29], 40u, 0xffu);
    freq4 |= unpack_left_shift_u64(src_p[30], 48u, 0xffu);
    freq4 |= unpack_left_shift_u64(src_p[31], 56u, 0xffu);
    memcpy(&dst_p->freq4, &freq4, sizeof(dst_p->freq4));

    return (0);
}

int ucr_01_rear_frequency_init(struct ucr_01_rear_frequency_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct ucr_01_rear_frequency_t));

    return 0;
}

double ucr_01_rear_frequency_freq1_encode(double value)
{
    return (double)(value);
}

double ucr_01_rear_frequency_freq1_decode(double value)
{
    return ((double)value);
}

bool ucr_01_rear_frequency_freq1_is_in_range(double value)
{
    (void)value;

    return (true);
}

double ucr_01_rear_frequency_freq2_encode(double value)
{
    return (double)(value);
}

double ucr_01_rear_frequency_freq2_decode(double value)
{
    return ((double)value);
}

bool ucr_01_rear_frequency_freq2_is_in_range(double value)
{
    (void)value;

    return (true);
}

double ucr_01_rear_frequency_freq3_encode(double value)
{
    return (double)(value);
}

double ucr_01_rear_frequency_freq3_decode(double value)
{
    return ((double)value);
}

bool ucr_01_rear_frequency_freq3_is_in_range(double value)
{
    (void)value;

    return (true);
}

double ucr_01_rear_frequency_freq4_encode(double value)
{
    return (double)(value);
}

double ucr_01_rear_frequency_freq4_decode(double value)
{
    return ((double)value);
}

bool ucr_01_rear_frequency_freq4_is_in_range(double value)
{
    (void)value;

    return (true);
}
